### ISSUE TITLE
A11.2 - Vista del registro de los usuarios

### ISSUE THREAD

**Issue by tomgalbar** [Stacking-Up/frontend#121]
## Detalles
Se deberá implementar un formulario en el frontend que permita el registro de los usuarios haciendo una petición POST a la API (repositorio authservice)

## Subtareas
- [x] Implementación del formulario de registro (con validaciones y gestión de errores)
- [x] Responsividad de la vista

## Imágenes
No procede

**Comment by borjar20** [comment]
Resuelto en [b81ff69](https://github.com/Stacking-Up/frontend/commit/b81ff69329e99e8b854f14d081a58f89c180d9ed)
