### ISSUE TITLE
RA1.1 - Refactorizar frontend

### ISSUE THREAD

**Issue by tomgalbar** [Stacking-Up/frontend#122]
## Detalles
Se deberá mejorar el código en general, cumplimentando la lista de subtareas que se detalla a continuación

## Subtareas
- [x] Marcado semántico (intentar no abusar de `<div>` y usar las tags concretas)
- [x] Componentizar el código común
- [x] Revisión de la lógica (promesas, funciones...)
- [x] Gestión de errores (back y front)
- [x] Guía de estilo (nombre de variables, funciones, tabulaciones...) - Quizás usando un .editor.config
- [x] Quitar los puntos suspensivos de las tags en la vista de detalles y smartSearch
- [x] Cambiar calendario de reservas por selectBox cuando sea por horas y meses, por días se usará el calendario

## Imágenes
No procede

**Comment by borjar20** [comment]
Resuelto en [4857f43](https://github.com/Stacking-Up/frontend/commit/4857f4394183b6bd17edabfa95be10c882200479)
