### ISSUE TITLE
RA1.4 - Implementar modificaciones del modelo en frontend

### ISSUE THREAD

**Issue by tomgalbar** [Stacking-Up/frontend#124]
## Detalles
Se deberán corregir/adaptar las vistas del frontend según se detalla a continuación:

## Subtareas
- [x] Añadir la cantidad a la tabla de items en la vista de SmartSearch
- [x] Utilizar los nuevos atributos Ciudad, Provincia y País para ahorrar peticiones a Mapbox
- [x] Eliminar la función que calcula el precio en el frontend
- [x] Implementar una alerta que avise que se alquilarán 2 meses si intentas alquilar 1 y X días y sólo esta por meses (igual para los días con las horas...)
- [x] Añadir las validaciones en frontend para los atributos startHour y endHour
- [x] Añadir disable al calendario del día siguiente a la hora de realizar un alquiler

## Imágenes
No procede

**Comment by borjar20** [comment]
Resuelto en [a1d6614](https://github.com/Stacking-Up/frontend/commit/a1d6614e83730a0b4ed610039a064a7c1e414735)
