### ISSUE TITLE
FA1.3 - Implementar la vista de valoraciones y recomendaciones

### ISSUE THREAD

**Issue by tomgalbar** [Stacking-Up/frontend#126]
## Detalles
Se deberá realizar la implementación prevista para el Sprint 3. Para la parte del frontend, ya existe una versión previa realizada en el Sprint 1, quizás sería interesante más que continuarla, coger el contenido de esa versión e implementarlo en la rama creada a partir de esta issue, de modo que tenga todo lo nuevo y así evitar tantos conflictos de una versión tan antigua.

En la imagen de debajo, se muestra la vista de perfil de usuario, la idea en el caso de esta tarea, sería implementar una sección de comentarios justo debajo de la sección de anuncios (parecida a Amazon). Es decir, primero se pone la cajita donde poner el comentario con la valoración (rating del 1 al 5) correctamente validado, y luego se mostrarían debajo todos los comentarios realizados por otros usuarios. 

La vista del perfil de usuario no está implementada aún pero puedes realizar tu tarea sin problema en un componente y luego se unifica (igualmente consultar el tablero kanban para ver su progreso). Por otro lado el endpoint del get de los ratings esta operativo, mientras que el del post está en proceso (consultar Stacking-Up/housekeeping#176 )

## Subtareas
- [x] Vistas de valoraciones y comentarios
- [x] Lógica y llamadas a la API (teniendo en cuenta validaciones y gestión de errores)
- [x] Responsividad de la vista

## Imágenes
Idea para la implementación:
![image](https://user-images.githubusercontent.com/72520181/160301706-16638aba-3e3a-4dd8-8f61-cb7846407347.png)

**Comment by serarirud** [comment]
He mergeado el contenido de la tarea #20 en esta tarea para continuarla aquí
