### ISSUE TITLE
A14.3 - Vista del panel de administración

### ISSUE THREAD

**Issue by tomgalbar** [Stacking-Up/frontend#130]
## Detalles
Se ha definido en el apartado de imágenes una primera idea de implementación por la que comenzar a trabajar, aunque no se tiene cerrada totalmente la idea de diseño o ideas de que implementar, así que es conveniente que cualquier duda se hable a @tomgalbar, @alesancor1 o @borjar20 para dejar decidido una posible decisión final sobre esta tarea. Además, es posible que surja la necesidad de crear nuevos endpoints para funcionalidades de administración que se os ocurran, por lo que cualquier necesidad debe ser comunicada con la mayor antelación posible.

## Subtareas
- [ ] Implementar la vista del panel de administración
- [ ] Lógica del panel de administración
- [ ] Responsividad de la vista

## Imágenes
No existe como tal un mockup definido para esto por lo que sería conveniente definir un mockup básico a papel o ordenador antes de comenzar y mostrarlo a los coordinadores y project manager para recibir feedback. Se debe pensar en el panel de administración como una vista que le permita hacer de todo (GET, POST, PUT, DELETE) al ADMIN desde una pantalla con una interfaz amigable y teniendo en cuenta siempre las validaciones y gestiones de errores. Además, sería muy conveniente reutilizar en la medida de lo posible los componentes que implementen toda esta lógica descrita anteriormente.

**Comment by serarirud** [comment]
La función de buscar datos en la tabla de la vista se va a dejar para el siguiente sprint. Esa funcionalidad consiste en un campo de búsqueda dentro del componente "Tabla" que filtra los datos que ya se encuentran en la vista, si hacer ninguna petición al servidor.
