### ISSUE TITLE
A16.1 - Implementación del sistema de pago

### ISSUE THREAD

**Issue by tomgalbar** [Stacking-Up/frontend#132]
## Detalles
Se deberá investigar el funcionamiento de las APIs de pago (por ejemplo la de Paypal) y ver como poder implementar eso para nuestros pagos.
Por otro lado, la idea para el pago es la siguiente (sujeta a cambios, comunicados con la mayor brevedad a @alesancor1, @tomgalbar o @borjar20):
1) Un usuario ve un espacio y realiza el pago, quedando retenido en nuestra cuenta. 
2) Una vez, se complete el período de alquiler y el inquilino recoja sus cosas y confirme que todo está bien (se debe implementar un botón de aceptación en la vista de detalles de un espacio) se procederá a pagar al arrendador (la confirmación por parte del inquilino es un atributo que se va a implementar en el alquiler, ver tarea Stacking-Up/housekeeping#171)

## Subtareas
- [x] Implementar la vista del pago (resumen del alquiler, dinero total, etc) con la generación de factura y contrato al pagar
- [ ] Implementar botón de confirmación de fin de alquiler correcto en la vista de detalles de un espacio que tenga alquilado y la lógica del pago al confirmarse pulsando dicho botón.
- [x] Factura y contrato (generación de un documento a modo de factura y un contrato genérico con los nombres y condiciones. Para esto se pueden buscar componentes de React ya existentes para facilitar la labor...)
- [x] Lógica del pago + pasarela de pago externa (paypal)
- [x] Responsividad de las vistas implementadas

## Imágenes
No hay mockups actulamente para ello, por lo que se puede guiar por las ideas comentadas anteriormente, intentando seguir la estética de la aplicación. Cualquier duda deberá ser comentada cuanto antes.

**Comment by Francisco-Borrego** [comment]
Prototipo inicial de vista para realizar pago. Ver la posibilidad de usar las facturas/checkout de Paypal en lugar de generar la factura por nuestra cuenta.

![Captura de pantalla de 2022-03-28 13-28-01](https://user-images.githubusercontent.com/72501583/160388572-f3ef950c-09f2-45a0-be57-44b39aad72a0.png)
