### ISSUE TITLE
A21.1 - Página de la política de privacidad (GDPR)

### ISSUE THREAD

**Issue by tomgalbar** [Stacking-Up/frontend#150]
## Detalles
Se deberá añadir al footer un enlace a la página de privacidad
Una vez hecho se deberá crear la propia página de privacidad con la información redactada en los documentos.

Se tratará de una vista muy simple que contará únicamente con página de privacidad (además de la tonav y footer ya existentes).

## Subtareas
No procede.

## Imágenes
No hay mockup pero hay bastante libertad para implementarlo, ya que es una vista muy simple que únicamente debe contener la información de privacidad. Hay libertad para basarse en la página de privacidad de cualquier otra página que parezca interesante o intuitiva y quede acorde a la nuestra.

**Comment by serarirud** [comment]
No he encontrado fallos mayores y doy por buena la revisión. 
Cosas a mejorar:
- El correo se podría meter en un <a href="mailto:correo@correo.es">correo@correo.es</a> para mayor comodidad y que sea congruente con los términos y condiciones de usos.
- Al hacer click en el enlace me carga la página con el scroll a medio bajar. Ese bug también ocurre con los términos y condiciones y @borjar20 está al tanto.
